services:
    data-hub-metrics-api:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${IMAGE_REPO}:${IMAGE_TAG}

    data-hub-metrics-api-dev:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                install_dev: y
        image:  ${IMAGE_REPO}-dev:${IMAGE_TAG}
        command: /bin/sh -c exit 0
        entrypoint: []

    redis:
        image: redis:7.4.2
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data

volumes:
    redis-data:
        driver: local
